services:
  - type: web
    name: bingo-agents-bot
    env: python
    envVars:
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: CARGO_NET_GIT_FETCH_WITH_CLI
        value: true
    buildCommand: "mkdir -p /tmp/cargo && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python agents.py"
    plan: free